### PR TITLE
fix: correct answer check

### LINKED ISSUE #13: Implement state for question component
- [ ] check correctness
- [ ] update question on check

### PR DESCRIPTION
**Pull request by BayableTeshome**

### CODE REVIEW

File: src/view/Question.js [hunk 1]
```diff
@@ -79,19 +89,25 @@ export const Question = () => {
       {nextButton && (
         <Stack alignItems={"center"}>
           <Typography variant="h4" mt={"40px"} mb={"30px"}>
-            Correct!
+            {currentAnswer ? "Correct!" : "Wrong!"}
```
Comment (TadieB) [inline src/view/Question.js]: change Wrong! with Sorry!

**Review by TadieB — APPROVED** [review]
